networks:
  monitoring:
    driver: bridge
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Guardian365
    networks:
      - monitoring
  mongo-express:
    depends_on:
      - db
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Guardian365
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH: false
    networks:
      - monitoring
  cache:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    networks:
      - monitoring 
      
  app:
    build: .
    command: node index.js
    # volumes:
    #   - .:/home/node/app
    #   - /home/node/app/node_modules
    depends_on:
      - mongo-express
      - cache
    # image: "node:alpine"
    # working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    # # volumes:
    # #   - ./:/home/node/abc
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    networks:
      - monitoring